# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GRAPLEr
email: graple@ufl.edu
description: > # this means to ignore newlines until "baseurl:"
  This page provides documentation for using GRAPLEr package to submit experiments
  for GRAPLE processing
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://smahesul.github.io" # the base hostname & protocol for your site
github_username:  GRAPLE

# Build settings
markdown: kramdown
